export interface BlogPost {
  slug: string;
  title_bg: string;
  title_en: string;
  excerpt_bg: string;
  excerpt_en: string;
  content_bg: string;
  content_en: string;
  date: string;
  image: string;
}

export const placeholderPosts: BlogPost[] = [
  {
    slug: 'klimatik-ne-ohlazhda',
    image: '/images/services/recharge.jpg',
    title_bg: 'Климатикът не охлажда — 7 причини и какво да направите',
    title_en: 'Car AC Not Cooling — 7 Causes and What to Do',
    excerpt_bg:
      'Климатикът духа топъл въздух? Разгледайте 7-те най-чести причини за слабо охлаждане и какво можете да направите, за да решите проблема бързо и без излишни разходи.',
    excerpt_en:
      'Is your car AC blowing warm air? Discover the 7 most common reasons for poor cooling and what you can do to fix the problem quickly without overspending.',
    content_bg:
      'Лятото е в разгара си, температурите минават 35°C, а климатикът на колата ви едва духа хладен въздух. Познато ли ви е? Това е един от най-честите проблеми, с които шофьорите идват при нас в HOT22. Нека разгледаме 7-те основни причини и какво стои зад всяка от тях.\n\n1. Нисък фреон\n\nНай-честата причина — около 60% от случаите. Фреонът се изпарява естествено с около 10-15% годишно, а ако има микро теч — и повече. Когато нивото падне, компресорът не може да създаде достатъчно налягане и охлаждането спада драстично. Решението е просто: диагностика + зареждане с правилното количество.\n\n2. Повреден компресор\n\nКомпресорът е сърцето на климатичната система. Ако чувате метален скърцащ звук при включване на AC или климатикът изобщо не реагира, може компресорът да е повреден. Ремонтът е по-сериозен, но навременната диагностика може да ви спести стотици левове.\n\n3. Теч в системата\n\nТечовете са коварни — понякога са толкова малки, че не се виждат с просто око. Появяват се по връзки, маркучи, кондензатора или изпарителя. В HOT22 използваме UV тест и електронен детектор, за да открием дори най-малкия теч.\n\n4. Електрически проблеми\n\nПрегорял предпазител, повреден превключвател или прекъснат кабел — електрическите проблеми могат да имитират механична повреда. Диагностиката с професионален скенер бързо разкрива дали проблемът е в електрическата верига.\n\n5. Замърсен кабинен филтър\n\nМного шофьори забравят за поленовия филтър. Когато е запушен, въздушният поток намалява драматично — климатикът работи, но в купето усещате едва лек полъх. Смяната отнема 5 минути и струва под 30 лв.\n\n6. Запушен кондензатор\n\nКондензаторът стои пред радиатора и лесно се запушва от насекоми, листа и мръсотия. Когато е замърсен, не може да отвежда топлината ефективно. Почистването е бърза процедура, но прави огромна разлика.\n\n7. Проблем с blend door актуатора\n\nТова е клапата, която насочва въздуха през топлообменника на парното или през изпарителя. Ако е заседнала в грешна позиция, може да получавате топъл въздух дори при работещ климатик. Обикновено се чува тихо щракане от зоната на таблото.\n\nКакво да направите?\n\nНе чакайте проблемът да се влоши. При първите признаци на слабо охлаждане заповядайте в HOT22 — правим пълна диагностика за 30-40 минути и ви даваме ясна картина какво трябва да се направи. Повечето проблеми се решават в рамките на един час, а зареждането с фреон е готово за под 30 минути.',
    content_en:
      'Summer is in full swing, temperatures are above 35°C, and your car AC is barely blowing cool air. Sound familiar? This is one of the most common issues drivers bring to us at HOT22. Let\'s look at the 7 main causes and what\'s behind each one.\n\n1. Low Refrigerant\n\nThe most common cause — about 60% of cases. Refrigerant naturally evaporates at around 10-15% per year, and if there\'s a micro-leak — even more. When the level drops, the compressor can\'t build enough pressure and cooling drops dramatically. The fix is simple: diagnostics + recharge with the correct amount.\n\n2. Failed Compressor\n\nThe compressor is the heart of the AC system. If you hear a metallic grinding sound when turning on the AC or the system doesn\'t respond at all, the compressor may be damaged. The repair is more serious, but early diagnostics can save you hundreds.\n\n3. System Leak\n\nLeaks are tricky — sometimes they\'re so small you can\'t see them with the naked eye. They appear at fittings, hoses, the condenser, or the evaporator. At HOT22, we use UV dye testing and electronic detectors to find even the tiniest leak.\n\n4. Electrical Issues\n\nA blown fuse, faulty switch, or broken wire — electrical problems can mimic mechanical failures. Diagnostics with a professional scanner quickly reveals whether the issue is in the electrical circuit.\n\n5. Clogged Cabin Filter\n\nMany drivers forget about the pollen filter. When it\'s clogged, airflow drops dramatically — the AC is working, but you barely feel a breeze inside the cabin. Replacing it takes 5 minutes and costs under 15 EUR.\n\n6. Blocked Condenser\n\nThe condenser sits in front of the radiator and easily gets clogged with insects, leaves, and dirt. When it\'s dirty, it can\'t dissipate heat effectively. Cleaning is a quick procedure, but it makes a huge difference.\n\n7. Blend Door Actuator Problem\n\nThis is the flap that directs air through either the heater core or the evaporator. If it\'s stuck in the wrong position, you may get warm air even with the AC running. You\'ll usually hear a faint clicking sound from behind the dashboard.\n\nWhat Should You Do?\n\nDon\'t wait for the problem to get worse. At the first signs of poor cooling, visit HOT22 — we run a full diagnostic in 30-40 minutes and give you a clear picture of what needs to be done. Most issues are resolved within an hour, and a refrigerant recharge is done in under 30 minutes.',
    date: '2026-03-20',
  },
  {
    slug: 'nepriyatna-mirizma-klimatik',
    image: '/images/services/ozone.jpg',
    title_bg: 'Неприятна миризма от климатика — причини и решение',
    title_en: 'Bad Smell from Car AC — Causes and Solutions',
    excerpt_bg:
      'Мирише неприятно от климатика на колата? Най-честите причини са бактерии и мухъл в изпарителя. Разберете какво причинява миризмата и как озонирането я премахва завинаги.',
    excerpt_en:
      'Getting a bad smell from your car AC? The most common causes are bacteria and mold in the evaporator. Find out what causes the odor and how ozone treatment eliminates it for good.',
    content_bg:
      'Включвате климатика и от решетките лъхва мирис на мухъл, мокро или нещо кисело? Този проблем е изключително разпространен и засяга почти всеки автомобил на 3-4 години. Добрата новина е, че се решава лесно, когато знаете причината.\n\nЗащо мирише?\n\nОсновният виновник е изпарителят — студеният елемент на климатика, скрит зад таблото. Когато климатикът работи, по повърхността на изпарителя се образува конденз — точно както по студена бутилка в горещ ден. Тази влага е идеална среда за размножаване на бактерии и мухъл. С времето колониите нарастват и започват да отделят характерната неприятна миризма. При включване на вентилатора въздухът минава през замърсения изпарител и разнася миризмата в целия салон.\n\nЗамърсен кабинен филтър\n\nВтората най-честа причина е старият кабинен филтър. Той задържа прах, полени, мръсотия и влага. Когато не е сменян повече от година, самият филтър започва да мирише. Мнозина се учудват колко голяма разлика прави една смяна за 20 лв.\n\nНатрупан конденз\n\nАко дренажният канал на изпарителя е запушен, кондензираната вода остава в кутията на изпарителя вместо да се оттича. Стоящата вода загнива бързо, особено през топлите месеци. Симптомът е лужа под колата от пасажерската страна — или по-точно, липсата на такава лужа когато климатикът работи.\n\nМиризма от цигарен дим\n\nЦигареният дим прониква дълбоко в тапицерията, таванния плат и вентилационните канали. Обикновеното почистване и ароматизатори само маскират проблема. Миризмата винаги се връща, защото частиците са навлезли в порите на материалите.\n\nКога е нужно озониране?\n\nОзонирането е единственият метод, който наистина решава проблема, а не го маскира. Озонът (O3) е мощен окислител, който унищожава бактерии, мухъл и миризми на молекулярно ниво. При нас в HOT22 процедурата отнема около 45 минути. Препоръчваме озониране в комбинация със смяна на кабинен филтър — така ефектът е максимален и трае 8-12 месеца.\n\nКак да предотвратите проблема?\n\nИзключвайте климатика 2-3 минути преди да спрете двигателя, но оставете вентилатора да работи. Така изпарителят изсъхва и не дава шанс на бактериите. Сменяйте кабинния филтър на всеки 12 месеца или 15 000 км. Ако усетите миризма, не чакайте — с времето става по-трудно за премахване. Обадете се в HOT22 или запишете час онлайн.',
    content_en:
      'You turn on the AC and a musty, damp, or sour smell hits you from the vents? This problem is extremely common and affects nearly every car after 3-4 years. The good news is that it\'s easy to fix once you know the cause.\n\nWhy Does It Smell?\n\nThe main culprit is the evaporator — the cold element of the AC hidden behind the dashboard. When the AC runs, condensation forms on the evaporator surface — just like on a cold bottle on a hot day. This moisture creates a perfect breeding ground for bacteria and mold. Over time, colonies grow and start producing that characteristic unpleasant smell. When you turn on the fan, air passes through the contaminated evaporator and carries the odor throughout the cabin.\n\nDirty Cabin Filter\n\nThe second most common cause is an old cabin filter. It traps dust, pollen, dirt, and moisture. When it hasn\'t been replaced for over a year, the filter itself starts to smell. Many people are surprised how big a difference a simple replacement makes.\n\nTrapped Condensation\n\nIf the evaporator drain is clogged, condensed water stays in the evaporator housing instead of draining out. Standing water goes stale quickly, especially during warm months. The symptom is a puddle under the car on the passenger side — or rather, the absence of such a puddle when the AC is running.\n\nCigarette Smoke Odor\n\nCigarette smoke penetrates deep into the upholstery, headliner, and ventilation ducts. Regular cleaning and air fresheners only mask the problem. The smell always comes back because the particles have embedded into the pores of the materials.\n\nWhen Is Ozone Treatment Needed?\n\nOzone treatment is the only method that truly solves the problem rather than masking it. Ozone (O3) is a powerful oxidizer that destroys bacteria, mold, and odors at the molecular level. At HOT22, the procedure takes about 45 minutes. We recommend ozone treatment combined with a cabin filter replacement — this maximizes the effect and it lasts 8-12 months.\n\nHow to Prevent the Problem?\n\nTurn off the AC 2-3 minutes before stopping the engine, but leave the fan running. This allows the evaporator to dry out and denies bacteria a chance to grow. Replace the cabin filter every 12 months or 15,000 km. If you notice a smell, don\'t wait — it gets harder to remove over time. Call HOT22 or book online.',
    date: '2026-03-18',
  },
  {
    slug: 'stranni-shumove-klimatik',
    image: '/images/services/compressor.jpg',
    title_bg: 'Странни шумове от климатика — кога е спешно?',
    title_en: 'Strange Noises from Your Car AC — When Is It Urgent?',
    excerpt_bg:
      'Чувате щракане, скърцане или бръмчене при включване на климатика? Научете какво означава всеки шум, кога е безобидно и кога трябва да действате веднага.',
    excerpt_en:
      'Hearing clicking, squealing, or buzzing when you turn on the AC? Learn what each noise means, when it\'s harmless, and when you need to act immediately.',
    content_bg:
      'Шумовете от климатичната система са нещо, което не бива да пренебрегвате. Някои са безобидни, но други сигнализират за проблем, който може да се влоши бързо и да ви излезе скъпо. Ето какво означава всеки тип шум.\n\nЩракане от таблото\n\nЛеко щракане при включване на климатика обикновено идва от blend door актуатора — клапата, която насочва въздуха. Ако щракането е кратко и еднократно, няма за какво да се притеснявате. Но ако е ритмично и продължава непрекъснато, актуаторът вероятно е износен и трябва да се смени. Цената е умерена — обикновено между 80 и 200 лв с труда.\n\nСкърцане при включване на AC\n\nТова е един от по-сериозните шумове. Високо скърцане или визг при натискане на бутона за AC обикновено идва от ремъка на компресора. Ако ремъкът е износен, хлабав или напукан, той се плъзга и издава този звук. Не чакайте — износен ремък може да се скъса по време на движение. В HOT22 проверката на ремъка отнема минути.\n\nБръмчене или жужене\n\nНискочестотно бръмчене при работещ климатик може да идва от компресора. Ако звукът се появява само при включен AC и изчезва при изключване, компресорът вероятно е натоварен заради нисък фреон или вътрешно износване. Диагностиката с манометри показва бързо дали проблемът е в налягането.\n\nМетално скърцане или дрънкане\n\nТова е аларменият звук. Метално стъргане или дрънкане от зоната на компресора означава вътрешна повреда — износени лагери, счупен бутален пръстен или разхлабена муфа. При такъв шум препоръчваме да изключите климатика веднага и да дойдете при нас колкото се може по-скоро. Продължителната работа на повреден компресор може да разпръсне метални частици в цялата система, което прави ремонта многократно по-скъп.\n\nТрополене от зоната на вентилатора\n\nЛистче, клонче или парче мръсотия, попаднало във вентилатора на купето, може да предизвика ритмично трополене. Обикновено е безобидно, но е дразнещо. Смяната на кабинния филтър и продухване на вентилатора решават проблема.\n\nКога е наистина спешно?\n\nВедна действайте при: метално стъргане или скърцане от компресора, внезапен силен удар при включване на AC, или ако климатикът спре да работи след шума. Тези симптоми означават механична повреда, която се влошава с всяка минута работа.\n\nВ HOT22 разполагаме с пълен набор диагностично оборудване за климатични системи. Проверката отнема 20-30 минути, а ранната диагностика може да ви спести между 200 и 800 лв на ремонт. Не пренебрегвайте шумовете — обадете се на 089 338 3443.',
    content_en:
      'Noises from the AC system are something you shouldn\'t ignore. Some are harmless, but others signal a problem that can escalate fast and cost you dearly. Here\'s what each type of noise means.\n\nClicking from the Dashboard\n\nA light click when turning on the AC usually comes from the blend door actuator — the flap that directs airflow. If the clicking is brief and happens once, there\'s nothing to worry about. But if it\'s rhythmic and continuous, the actuator is likely worn and needs replacing. The cost is moderate — typically between 40 and 100 EUR including labor.\n\nSquealing When AC Turns On\n\nThis is one of the more serious noises. A high-pitched squeal or screech when you hit the AC button usually comes from the compressor belt. If the belt is worn, loose, or cracked, it slips and makes this sound. Don\'t wait — a worn belt can snap while driving. At HOT22, checking the belt takes minutes.\n\nBuzzing or Humming\n\nA low-frequency hum with the AC running can come from the compressor. If the sound only appears with AC on and disappears when it\'s off, the compressor is likely strained due to low refrigerant or internal wear. A pressure gauge diagnostic quickly shows whether the issue is related to refrigerant levels.\n\nMetallic Grinding or Rattling\n\nThis is the alarm sound. Metallic scraping or rattling from the compressor area means internal damage — worn bearings, a broken piston ring, or a loose clutch. If you hear this, we recommend turning off the AC immediately and visiting us as soon as possible. Running a damaged compressor can spread metal particles throughout the entire system, making the repair many times more expensive.\n\nKnocking from the Fan Area\n\nA leaf, twig, or piece of debris caught in the cabin fan can cause rhythmic knocking. It\'s usually harmless but annoying. A cabin filter replacement and fan blowout solves it.\n\nWhen Is It Truly Urgent?\n\nAct immediately if you hear: metallic scraping or grinding from the compressor, a sudden loud bang when AC turns on, or if the AC stops working after the noise. These symptoms mean mechanical damage that worsens with every minute of operation.\n\nAt HOT22, we have a full set of diagnostic equipment for AC systems. The check takes 20-30 minutes, and early diagnostics can save you 100-400 EUR on repairs. Don\'t ignore the noises — call 089 338 3443.',
    date: '2026-03-15',
  },
  {
    slug: 'parnoto-ne-gree',
    image: '/images/services/heater.jpg',
    title_bg: 'Парното не грее — 5 чести причини',
    title_en: 'Car Heater Not Working — 5 Common Causes',
    excerpt_bg:
      'Парното на колата духа студен въздух в средата на зимата? Разберете 5-те най-чести причини — от запушен радиатор на парното до проблем с термостата — и как да ги решите.',
    excerpt_en:
      'Car heater blowing cold air in the middle of winter? Learn about the 5 most common causes — from a clogged heater core to thermostat issues — and how to fix them.',
    content_bg:
      'Навън е минус 5, а от парното духа едва хладък въздух. Познат сценарий за много шофьори, особено с коли на повече от 7-8 години. Нека разгледаме 5-те причини, които виждаме най-често в нашия сервиз.\n\n1. Запушен радиатор на парното\n\nТова е причина номер едно. Радиаторът на парното (heater core) е малък топлообменник зад таблото, през който минава гореща охладителна течност. С годините вътрешността му се запушва от утайки, ръжда и стар антифриз. Симптомите са характерни: парното грее слабо или от едната страна духа топло, а от другата — студено. В HOT22 правим промиване на радиатора на парното, което в 70% от случаите решава проблема без нужда от скъпа подмяна.\n\n2. Проблем с термостата\n\nТермостатът регулира потока на охладителна течност. Когато заседне в отворена позиция, двигателят не достига нормалната си работна температура от 85-95°C, а остава на 60-70°C. Резултатът: парното грее, но не достатъчно. Характерен симптом е стрелката на температурата да не достига средата на скалата дори след 15-20 минути шофиране. Подмяната на термостат е бърза и сравнително евтина — обикновено между 50 и 120 лв.\n\n3. Ниско ниво на охладителна течност\n\nАко нивото на антифриза е паднало, няма достатъчно течност да циркулира през радиатора на парното. Причините може да са теч от маркуч, радиатор или водна помпа. Проверете разширителния съд — нивото трябва да е между MIN и MAX маркировките. Ниско ниво без видим теч може да означава проблем с уплътнението на главата — при такъв случай не отлагайте диагностиката.\n\n4. Заседнала клапа (blend door)\n\nBlend door е клапата, която контролира пропорцията на горещ и студен въздух. Когато заседне или актуаторът й се повреди, парното може да духа само студен въздух, независимо на каква температура е зададено. Обикновено се чува тихо щракане при завъртане на копчето за температура. Ремонтът изисква достъп зад таблото, което отнема повече време, но е решим проблем.\n\n5. Въздушна пробка в охладителната система\n\nСлед смяна на антифриз или ремонт на охладителната система може да остане въздух вътре. Въздушният мехур блокира циркулацията през радиатора на парното. Симптомът е парно, което грее на моменти — топло за 30 секунди, после студено за минута, после пак топло. Обезвъздушаването е проста процедура, но изисква правилна техника.\n\nКакво да направите?\n\nНе карайте цяла зима с нефункциониращо парно — освен дискомфорта, това е и въпрос на безопасност. Без работещо парно стъклата се замъгляват и видимостта пада рязко. При нас в HOT22 правим пълна диагностика на отоплителната система, промиваме радиатори и отстраняваме проблеми бързо. Свържете се с нас на 089 338 3443.',
    content_en:
      'It\'s minus 5 outside, and the heater is barely blowing lukewarm air. A familiar scenario for many drivers, especially with cars older than 7-8 years. Let\'s look at the 5 causes we see most often at our shop.\n\n1. Clogged Heater Core\n\nThis is the number one cause. The heater core is a small heat exchanger behind the dashboard through which hot coolant flows. Over the years, its interior gets clogged with sediment, rust, and old antifreeze. The symptoms are distinctive: the heater warms poorly, or one side blows warm while the other blows cold. At HOT22, we flush the heater core, which resolves the issue in 70% of cases without the need for an expensive replacement.\n\n2. Thermostat Problem\n\nThe thermostat regulates the flow of coolant. When it gets stuck in the open position, the engine doesn\'t reach its normal operating temperature of 85-95°C and stays at 60-70°C. The result: the heater works, but not well enough. A telltale sign is the temperature gauge not reaching the middle of the scale even after 15-20 minutes of driving. Replacing a thermostat is quick and relatively cheap — usually between 25 and 60 EUR.\n\n3. Low Coolant Level\n\nIf the antifreeze level has dropped, there isn\'t enough fluid to circulate through the heater core. The causes could be a leaking hose, radiator, or water pump. Check the expansion tank — the level should be between the MIN and MAX markings. A low level with no visible leak could indicate a head gasket issue — don\'t delay diagnostics in that case.\n\n4. Stuck Blend Door\n\nThe blend door is the flap that controls the mix of hot and cold air. When it gets stuck or its actuator fails, the heater may only blow cold air regardless of the temperature setting. You\'ll usually hear a faint clicking sound when turning the temperature knob. The repair requires access behind the dashboard, which takes more time, but it\'s a solvable problem.\n\n5. Air Lock in the Cooling System\n\nAfter a coolant change or cooling system repair, air can get trapped inside. The air bubble blocks circulation through the heater core. The symptom is intermittent heating — warm for 30 seconds, then cold for a minute, then warm again. Bleeding the system is a simple procedure, but it requires proper technique.\n\nWhat Should You Do?\n\nDon\'t drive all winter with a non-functioning heater — beyond discomfort, it\'s a safety issue. Without a working heater, windows fog up and visibility drops sharply. At HOT22, we perform complete heating system diagnostics, flush heater cores, and fix problems quickly. Contact us at 089 338 3443.',
    date: '2026-03-12',
  },
  {
    slug: 'r134a-ili-r1234yf',
    image: '/images/services/recharge.jpg',
    title_bg: 'R134a или R1234yf — кой фреон е за вашата кола?',
    title_en: 'R134a or R1234yf — Which Refrigerant Does Your Car Need?',
    excerpt_bg:
      'Не знаете кой фреон използва колата ви? Разберете разликата между R134a и R1234yf, кои автомобили използват кой тип и защо смесването им е опасно за системата.',
    excerpt_en:
      'Not sure which refrigerant your car uses? Learn the difference between R134a and R1234yf, which cars use which type, and why mixing them is dangerous for the system.',
    content_bg:
      'При зареждане на климатика един от първите въпроси е: какъв фреон ползва колата ми? Грешният отговор може да доведе до повреда на цялата климатична система. Ето всичко, което трябва да знаете.\n\nR134a — класиката\n\nR134a е хладилен агент, използван масово от 1994 година насам. Преди него се използваше R12, който беше забранен заради разрушаване на озоновия слой. R134a е надежден, изпитан и сравнително евтин — зареждането обикновено излиза между 80 и 120 лв. Повечето автомобили, произведени до 2015-2017 г., използват R134a.\n\nR1234yf — новото поколение\n\nОт 2017 г. всички нови автомобили в ЕС задължително използват R1234yf. Причината е екологична — R1234yf има потенциал за глобално затопляне (GWP) от едва 4, докато R134a има GWP от 1430. Това е 350 пъти по-малко въздействие върху климата. Но има и недостатък: R1234yf е значително по-скъп. Зареждането обикновено струва 180-280 лв — 2-3 пъти повече от R134a.\n\nКой фреон е за вашата кола?\n\nИма три лесни начина да разберете. Първо, погледнете стикера под капака — обикновено е на радиаторната траверса или близо до куплунга за зареждане. На него пише типът фреон и точното количество в грамове. Второ, проверете годината на производство — ако колата е произведена след 2017 г., почти сигурно е R1234yf. Трето, формата на куплунга за зареждане е различна при двата типа — те са специално направени несъвместими, за да се предотврати случайно смесване.\n\nЗащо не бива да ги смесвате?\n\nСмесването на R134a и R1234yf е една от най-лошите неща, които можете да направите на климатичната система. Двата фреона работят при различни налягания и имат различни химични свойства. Смесването може да доведе до: повреда на компресора заради неправилно налягане, разяждане на уплътненията, намалена ефективност на охлаждането и скъп ремонт с пълна подмяна на фреона и промиване на системата.\n\nВнимание с евтините сервизи\n\nНякои нелицензирани сервизи зареждат с R134a системи, проектирани за R1234yf, за да спестят от цената. В краткосрочен план климатикът може да заработи, но в дългосрочен — щетите са неизбежни. Винаги питайте какъв фреон зареждат и настоявайте за правилния тип.\n\nВ HOT22 работим и с двата типа фреон с професионални станции, които автоматично разпознават и не допускат смесване. Преди всяко зареждане правим проверка на чистотата на фреона в системата. Ако не сте сигурни кой тип ползва вашият автомобил, просто ни се обадете или пишете — ще ви кажем за секунди.',
    content_en:
      'When recharging your AC, one of the first questions is: what refrigerant does my car use? The wrong answer can lead to damage to the entire AC system. Here\'s everything you need to know.\n\nR134a — The Classic\n\nR134a is a refrigerant used widely since 1994. Before it, R12 was used but was banned for depleting the ozone layer. R134a is reliable, proven, and relatively affordable — a recharge typically costs 40-60 EUR. Most cars manufactured until 2015-2017 use R134a.\n\nR1234yf — The New Generation\n\nSince 2017, all new cars in the EU are required to use R1234yf. The reason is environmental — R1234yf has a global warming potential (GWP) of just 4, while R134a has a GWP of 1430. That\'s 350 times less climate impact. But there\'s a drawback: R1234yf is significantly more expensive. A recharge typically costs 90-140 EUR — 2-3 times more than R134a.\n\nWhich Refrigerant Is for Your Car?\n\nThere are three easy ways to find out. First, look at the sticker under the hood — it\'s usually on the radiator support or near the charging port. It lists the refrigerant type and the exact amount in grams. Second, check the year of manufacture — if the car was made after 2017, it\'s almost certainly R1234yf. Third, the charging port shape is different for the two types — they\'re intentionally made incompatible to prevent accidental mixing.\n\nWhy You Must Never Mix Them\n\nMixing R134a and R1234yf is one of the worst things you can do to an AC system. The two refrigerants operate at different pressures and have different chemical properties. Mixing can lead to: compressor damage due to incorrect pressure, seal degradation, reduced cooling efficiency, and an expensive repair involving complete refrigerant replacement and system flushing.\n\nBeware of Cheap Shops\n\nSome unlicensed shops charge R134a into systems designed for R1234yf to save on cost. In the short term, the AC may work, but long-term damage is inevitable. Always ask what refrigerant they\'re using and insist on the correct type.\n\nAt HOT22, we work with both refrigerant types using professional stations that automatically identify and prevent cross-contamination. Before every recharge, we check the purity of the refrigerant in the system. If you\'re not sure which type your car uses, just call or message us — we\'ll tell you in seconds.',
    date: '2026-03-08',
  },
  {
    slug: 'ozoniranie-kak-raboti',
    image: '/images/services/ozone.jpg',
    title_bg: 'Озониране на автомобил — как работи и кога е нужно?',
    title_en: 'Car Ozone Treatment — How It Works and When You Need It',
    excerpt_bg:
      'Научете как озонирането унищожава бактерии и миризми в колата стъпка по стъпка. Разберете кога е нужно, колко време отнема и колко дълго трае ефектът.',
    excerpt_en:
      'Learn how ozone treatment destroys bacteria and odors in your car step by step. Find out when it\'s needed, how long it takes, and how long the effect lasts.',
    content_bg:
      'Озонирането е дума, която чувате все по-често, но какво точно стои зад нея? Как един газ може да премахне миризми, които никакво почистване не може? Нека обясним процеса просто и ясно.\n\nКакво е озон?\n\nОзонът (O3) е форма на кислород с три атома вместо обичайните два (O2). Тази допълнителна молекула го прави изключително реактивен — озонът се „закача" за органични замърсители, бактерии и миризливи молекули и ги разрушава чрез окисление. След 20-30 минути нестабилният трети атом се отделя и озонът се връща обратно до обикновен кислород. Не остават никакви химикали или остатъци.\n\nКак протича процедурата?\n\nВ HOT22 следваме точен протокол. Стъпка 1: Почистваме купето от видими замърсявания и изваждаме подложките. Стъпка 2: Поставяме професионален озонов генератор в купето. Стъпка 3: Затваряме всички прозорци и врати, включваме вентилацията на рециркулация и пускаме генератора. Стъпка 4: Генераторът работи 25-30 минути при концентрация, достатъчна за унищожаване на 99.9% от бактериите. Стъпка 5: Проветряваме автомобила 10-15 минути. Целият процес отнема около 50-60 минути.\n\nКакво унищожава озонът?\n\nСписъкът е впечатляващ: бактерии (стафилококи, стрептококи, E.coli), вируси, мухъл и гъбични спори, миризми от цигари и тютюн, миризми от домашни любимци, миризми от храна и разлято мляко, алергени и полени. Озонът прониква навсякъде — в тапицерията, килимите, вентилационните канали, под седалките. Места, до които ръчното почистване просто не достига.\n\nКога е нужно озониране?\n\nПрепоръчваме го в няколко случая: когато имате упорита миризма, която не изчезва след почистване; при покупка на употребяван автомобил — не знаете какво е ставало в купето; ако превозвате домашни любимци редовно; след боледуване с вирусна инфекция; ако пушите в колата; и поне веднъж годишно като профилактика. Особено препоръчваме процедурата след зимния сезон, когато колата е била затворена дълго време с натрупана влага.\n\nКолко дълго трае ефектът?\n\nПри нормална употреба ефектът от озонирането трае 8-12 месеца. Ако комбинирате с нов кабинен филтър и спазвате простото правило да изключвате AC 2-3 минути преди спиране на двигателя, ефектът може да издържи и по-дълго. Цената на процедурата при нас в HOT22 Варна е достъпна и се отплаща многократно с комфорт и здраве. Свържете се с нас за повече информация.',
    content_en:
      'Ozone treatment is a term you hear more and more often, but what exactly is behind it? How can a gas remove odors that no amount of cleaning can? Let\'s explain the process simply and clearly.\n\nWhat Is Ozone?\n\nOzone (O3) is a form of oxygen with three atoms instead of the usual two (O2). This extra molecule makes it extremely reactive — ozone attaches to organic contaminants, bacteria, and odor molecules and destroys them through oxidation. After 20-30 minutes, the unstable third atom detaches and ozone converts back to regular oxygen. No chemicals or residues are left behind.\n\nHow Does the Procedure Work?\n\nAt HOT22, we follow a precise protocol. Step 1: We clean the cabin of visible contaminants and remove the floor mats. Step 2: We place a professional ozone generator inside the cabin. Step 3: We close all windows and doors, set the ventilation to recirculation mode, and start the generator. Step 4: The generator runs for 25-30 minutes at a concentration sufficient to destroy 99.9% of bacteria. Step 5: We ventilate the car for 10-15 minutes. The entire process takes about 50-60 minutes.\n\nWhat Does Ozone Destroy?\n\nThe list is impressive: bacteria (staphylococci, streptococci, E.coli), viruses, mold and fungal spores, cigarette and tobacco odors, pet odors, food smells and spilled milk, allergens and pollen. Ozone penetrates everywhere — into the upholstery, carpets, ventilation ducts, under the seats. Places that manual cleaning simply cannot reach.\n\nWhen Is Ozone Treatment Needed?\n\nWe recommend it in several cases: when you have a stubborn odor that doesn\'t go away after cleaning; when buying a used car — you don\'t know what happened in the cabin; if you regularly transport pets; after illness with a viral infection; if you smoke in the car; and at least once a year as preventive maintenance. We especially recommend the procedure after winter, when the car has been closed for a long time with accumulated moisture.\n\nHow Long Does the Effect Last?\n\nWith normal use, the ozone treatment effect lasts 8-12 months. If you combine it with a new cabin filter and follow the simple rule of turning off the AC 2-3 minutes before stopping the engine, the effect can last even longer. The price of the procedure at our HOT22 location in Varna is affordable and pays for itself many times over in comfort and health. Contact us for more information.',
    date: '2026-03-05',
  },
  {
    slug: 'podgotvete-kolata-za-lyatoto',
    image: '/images/services/workshop.jpg',
    title_bg: 'Как да подготвите колата за лятото — 5 стъпки',
    title_en: 'How to Prepare Your Car for Summer — 5 Steps',
    excerpt_bg:
      'Лятото идва и колата ви трябва да е готова. Следвайте тези 5 стъпки за подготовка на климатика, охладителната система и филтрите, за да карате комфортно и без повреди.',
    excerpt_en:
      'Summer is coming and your car needs to be ready. Follow these 5 steps to prepare your AC, cooling system, and filters so you can drive comfortably and avoid breakdowns.',
    content_bg:
      'Всяка година по едно и също време телефонът ни в HOT22 Варна започва да звъни нон-стоп — идват първите горещи дни и стотици шофьори едновременно разбират, че климатикът им не работи. Не бъдете от тях. Ето 5 стъпки, които можете да направите предварително.\n\nСтъпка 1: Проверете климатика рано\n\nНе чакайте юни. Включете климатика още през март или април и вижте дали охлажда нормално. Ако въздухът не е ледено студен за 2-3 минути, нещо не е наред. По-добре е да дойдете в сервиза през април, когато нямаме опашки, отколкото през юли, когато чакането може да е дни.\n\nСтъпка 2: Заредете фреона\n\nАко климатикът охлажда, но не толкова силно колкото преди, вероятно нивото на фреон е паднало. Нормалната загуба е 10-15% годишно. Зареждането отнема 20-30 минути и е най-честата услуга, която правим. В HOT22 зареждаме и R134a, и R1234yf с професионална станция, която дозира грам по грам.\n\nСтъпка 3: Сменете кабинния филтър\n\nФилтърът на купето е евтин компонент, който мнозина пренебрегват. Но замърсеният филтър намалява въздушния поток с до 40%, натоварва вентилатора и може да причини неприятна миризма. Смяната отнема буквално 5 минути. Препоръчваме да го сменяте поне веднъж годишно, а ако карате много по запрашени пътища — на всеки 6 месеца.\n\nСтъпка 4: Проверете охладителната течност\n\nАнтифризът не е само за зимата — той предпазва двигателя от прегряване и през лятото. Проверете нивото в разширителния съд и цвета на течността. Ако е кафеникава или мътна вместо зелена/розова/синя, време е за смяна. Концентрацията трябва да осигурява защита от -35°C до +108°C.\n\nСтъпка 5: Инспектирайте налягането на гумите\n\nМоже да ви изненада, но налягането на гумите се променя с температурата — за всеки 10°C увеличение, налягането расте с около 0.1 бара. Гуми, които са били коректно напомпани при 5°C, може да са с надмерно налягане при 35°C. Проверявайте налягането сутрин, преди колата да е карана.\n\nБонус: Озониране след зимата\n\nПрез зимата колата е затворена повече, прозорците рядко се отварят, и влагата се натрупва. Пролетта е идеалният момент за озониране — премахвате бактериите и миризмите и започвате сезона с чисто купе.\n\nВ HOT22 предлагаме пълен пакет за лятна подготовка — проверка на климатика, зареждане, смяна на филтър и озониране. Елате преди да удари жегата — така и цената е по-добра, и обслужването е по-бързо. Обадете се на 089 338 3443 или запишете час онлайн.',
    content_en:
      'Every year around the same time, our phone at HOT22 Varna starts ringing nonstop — the first hot days arrive and hundreds of drivers simultaneously discover their AC isn\'t working. Don\'t be one of them. Here are 5 steps you can take in advance.\n\nStep 1: Check Your AC Early\n\nDon\'t wait until June. Turn on the AC in March or April and see if it cools normally. If the air isn\'t ice-cold within 2-3 minutes, something is off. It\'s better to visit the shop in April when there are no queues than in July when the wait can be days.\n\nStep 2: Recharge the Refrigerant\n\nIf the AC cools but not as strongly as before, the refrigerant level has likely dropped. Normal loss is 10-15% per year. Recharging takes 20-30 minutes and is the most common service we perform. At HOT22, we recharge both R134a and R1234yf with a professional station that doses gram by gram.\n\nStep 3: Replace the Cabin Filter\n\nThe cabin filter is a cheap component that many neglect. But a dirty filter reduces airflow by up to 40%, overworks the fan, and can cause unpleasant odors. Replacement takes literally 5 minutes. We recommend changing it at least once a year, and if you drive on dusty roads frequently — every 6 months.\n\nStep 4: Check the Coolant\n\nAntifreeze isn\'t just for winter — it protects the engine from overheating in summer too. Check the level in the expansion tank and the color of the fluid. If it\'s brownish or murky instead of green/pink/blue, it\'s time for a change. The concentration should provide protection from -35°C to +108°C.\n\nStep 5: Inspect Tire Pressure\n\nThis might surprise you, but tire pressure changes with temperature — for every 10°C increase, pressure rises by about 0.1 bar. Tires that were correctly inflated at 5°C may be over-inflated at 35°C. Check pressure in the morning before the car has been driven.\n\nBonus: Ozone Treatment After Winter\n\nDuring winter, the car stays closed more, windows are rarely opened, and moisture accumulates. Spring is the ideal time for ozone treatment — you remove bacteria and odors and start the season with a clean cabin.\n\nAt HOT22, we offer a complete summer prep package — AC check, recharge, filter replacement, and ozone treatment. Come before the heat hits — the price is better and the service is faster. Call 089 338 3443 or book online.',
    date: '2026-03-01',
  },
  {
    slug: 'zarezhdane-klimatik-varna',
    image: '/images/services/hero.jpg',
    title_bg: 'Зареждане на климатик Варна — как да изберете сервиз?',
    title_en: 'Car AC Recharge in Varna — How to Choose a Service Shop?',
    excerpt_bg:
      'Търсите зареждане на автоклиматик във Варна? Научете на какво да обърнете внимание при избора на сервиз, защо евтиното зареждане може да ви излезе скъпо и какво предлага HOT22.',
    excerpt_en:
      'Looking for a car AC recharge in Varna? Learn what to look for when choosing a service shop, why cheap recharges can cost you more, and what HOT22 offers.',
    content_bg:
      'Във Варна има десетки сервизи, които предлагат зареждане на автоклиматик. Цените варират от 50 до 300 лв и разликата не е само в цената на фреона. Ето какво трябва да знаете, за да не хвърлите парите си напразно.\n\nЗащо професионалното оборудване е важно?\n\nЗареждането на климатик не е просто наливане на фреон. Правилният процес включва: извличане на стария фреон и измерване на количеството му (за да се разбере дали има теч), вакуумиране на системата за минимум 15 минути (за отстраняване на влага и въздух), тест за задържане на вакуум (проверка за течове) и едва тогава зареждане с точно определеното количество фреон — грам по грам.\n\nПрофесионалните станции за зареждане струват десетки хиляди левове. Те автоматизират целия процес и елиминират човешката грешка. Евтините сервизи често работят с ръчни манометри и „на око" — дозират приблизително, пропускат вакуумирането или го правят за 2-3 минути вместо за 15.\n\nКакво може да се обърка?\n\nНедостатъчно вакуумиране означава влага в системата. Влагата реагира с фреона и образува киселини, които разяждат компресора отвътре. Повредата се проявява 6-12 месеца по-късно и струва 500-1500 лв за ремонт. Неточно количество фреон — както твърде малко, така и твърде много — натоварва компресора и намалява ефективността. Зареждане с грешен тип фреон може да разруши цялата система.\n\nНа какво да обърнете внимание?\n\nПитайте какво оборудване използват — автоматична станция или ръчни манометри? Искайте разпечатка от станцията — тя показва точното количество извлечен и зареден фреон, времето на вакуумиране и резултата от теста за течове. Попитайте дали правят проверка за течове преди зареждане — ако не, рискувате да заредите фреон, който ще изтече за седмица. Проверете дали работят с вашия тип фреон — не всички сервизи имат оборудване за R1234yf.\n\nЗащо HOT22?\n\nВ нашия сервиз във Варна разполагаме с професионална автоматична станция от последно поколение, която работи и с R134a, и с R1234yf. Всеки клиент получава разпечатка с точните параметри. Преди зареждане задължително проверяваме за течове с електронен детектор. Процесът отнема 25-40 минути — без прескачане на стъпки. Намираме се на удобна локация и можете да запазите час онлайн, за да не чакате.\n\nНе рискувайте с гаражен сервиз заради 30 лв разлика. Повреден компресор заради некачествено зареждане струва 10 пъти повече. Обадете се на 089 338 3443 или пишете онлайн.',
    content_en:
      'In Varna, there are dozens of shops offering car AC recharges. Prices range from 25 to 150 EUR, and the difference isn\'t just in the cost of refrigerant. Here\'s what you need to know to avoid wasting your money.\n\nWhy Does Professional Equipment Matter?\n\nRecharging an AC isn\'t simply pouring in refrigerant. The proper process includes: extracting old refrigerant and measuring the amount (to determine if there\'s a leak), vacuuming the system for at least 15 minutes (to remove moisture and air), a vacuum hold test (to check for leaks), and only then charging with the precisely specified amount of refrigerant — gram by gram.\n\nProfessional recharging stations cost tens of thousands of euros. They automate the entire process and eliminate human error. Cheap shops often work with manual gauges and estimates — dosing approximately, skipping the vacuum step or doing it for 2-3 minutes instead of 15.\n\nWhat Can Go Wrong?\n\nInsufficient vacuuming means moisture in the system. Moisture reacts with refrigerant and forms acids that corrode the compressor from within. The damage shows up 6-12 months later and costs 250-750 EUR to repair. Incorrect refrigerant amount — both too little and too much — strains the compressor and reduces efficiency. Charging with the wrong type of refrigerant can destroy the entire system.\n\nWhat Should You Look For?\n\nAsk what equipment they use — automatic station or manual gauges? Request a printout from the station — it shows the exact amount of extracted and charged refrigerant, vacuum time, and leak test results. Ask if they check for leaks before charging — if not, you risk charging refrigerant that will leak out within a week. Check if they handle your refrigerant type — not all shops have R1234yf equipment.\n\nWhy HOT22?\n\nAt our shop in Varna, we have a latest-generation professional automatic station that works with both R134a and R1234yf. Every client receives a printout with exact parameters. Before recharging, we always check for leaks with an electronic detector. The process takes 25-40 minutes — no steps skipped. We\'re conveniently located and you can book online to avoid waiting.\n\nDon\'t risk a garage shop over a 15 EUR difference. A compressor damaged by a poor recharge costs 10 times more. Call 089 338 3443 or write to us online.',
    date: '2026-02-25',
  },
  {
    slug: 'avtoklimatici-varna-rakovodstvo',
    image: '/images/services/workshop.jpg',
    title_bg: 'Автоклиматици Варна — пълно ръководство за шофьори',
    title_en: 'Car AC in Varna — Complete Driver\'s Guide',
    excerpt_bg:
      'Всичко, което трябва да знаете за автоклиматика — как работи, какви проблеми да очаквате, какъв е графикът за поддръжка и кои услуги предлага HOT22 във Варна.',
    excerpt_en:
      'Everything you need to know about car AC — how it works, what problems to expect, the maintenance schedule, and what services HOT22 offers in Varna.',
    content_bg:
      'Автоклиматикът е система, без която модерното шофиране е немислимо. Но повечето шофьори не разбират как работи и какво трябва да правят, за да я поддържат. Ето пълното ръководство.\n\nКак работи автоклиматикът?\n\nСистемата работи на принципа на хладилника. Компресорът сгъстява газообразния фреон, който се нагрява. Горещият фреон минава през кондензатора (пред радиатора), където се охлажда и се втечнява. Течният фреон минава през разширителен клапан, където налягането пада рязко и фреонът се изпарява в изпарителя зад таблото. При изпаряването поглъща топлина от въздуха в купето — и точно така ви е хладно. Целият цикъл се повтаря непрекъснато.\n\nНай-честите проблеми\n\nОт нашия опит в HOT22, ето класацията: нисък фреон (55% от посещенията), замърсен кабинен филтър (20%), неприятна миризма от изпарителя (15%), проблем с компресора (5%), електрически проблеми (3%), теч в системата (2%). Повечето проблеми се решават бързо и без големи разходи — стига да не се чака, докато се влошат.\n\nГрафик за поддръжка\n\nНа всеки 12 месеца: смяна на кабинен филтър. На всеки 2 години: проверка и при нужда зареждане на фреон. На всеки 2-3 години: озониране на купето. На всеки 5 години: проверка на състоянието на маркучи и уплътнения. При първи признак: диагностика при шум, слабо охлаждане или миризма. Този график е ориентировъчен — ако карате много или в тежки условия (градски трафик, горещ климат), интервалите може да са по-кратки.\n\nУслуги в HOT22 Варна\n\nДиагностика на климатичната система — с професионален скенер и манометри проверяваме налягането, температурите и електрическите параметри. Зареждане с фреон R134a и R1234yf — с автоматична станция, грам по грам. Откриване на течове — UV тест и електронен детектор. Ремонт на компресори — от смяна на муфа до пълна подмяна. Ремонт на парно — промиване и подмяна на радиатор на парното. Озониране и дезинфекция — за чист и здравословен въздух. Смяна на кабинен филтър — бързо и на достъпна цена.\n\nКога да посетите сервиз?\n\nНе чакайте лятото. Най-добрият момент за проверка на климатика е пролетта — март и април. Сервизите не са натоварени, можете да си изберете удобен час, а цените на някои услуги може да са по-изгодни. В HOT22 можете да запишете час онлайн или да се обадите на 089 338 3443. Намираме се във Варна и обслужваме коли от всички марки.',
    content_en:
      'Car AC is a system that modern driving is unthinkable without. But most drivers don\'t understand how it works or what they need to do to maintain it. Here\'s the complete guide.\n\nHow Does Car AC Work?\n\nThe system works on the same principle as a refrigerator. The compressor compresses gaseous refrigerant, which heats up. The hot refrigerant passes through the condenser (in front of the radiator), where it cools and liquefies. The liquid refrigerant passes through an expansion valve, where pressure drops sharply and the refrigerant evaporates in the evaporator behind the dashboard. During evaporation, it absorbs heat from the cabin air — and that\'s how you stay cool. The entire cycle repeats continuously.\n\nMost Common Problems\n\nFrom our experience at HOT22, here\'s the ranking: low refrigerant (55% of visits), dirty cabin filter (20%), unpleasant smell from the evaporator (15%), compressor issues (5%), electrical problems (3%), system leak (2%). Most problems are resolved quickly and without major expense — as long as you don\'t wait until they get worse.\n\nMaintenance Schedule\n\nEvery 12 months: cabin filter replacement. Every 2 years: check and if needed recharge the refrigerant. Every 2-3 years: cabin ozone treatment. Every 5 years: inspect hoses and seals. At the first sign: diagnostics for noise, weak cooling, or odor. This schedule is approximate — if you drive a lot or in harsh conditions (city traffic, hot climate), intervals may be shorter.\n\nServices at HOT22 Varna\n\nAC system diagnostics — using a professional scanner and gauges, we check pressure, temperatures, and electrical parameters. Refrigerant recharge R134a and R1234yf — with an automatic station, gram by gram. Leak detection — UV dye test and electronic detector. Compressor repair — from clutch replacement to full rebuild. Heater repair — flushing and replacing the heater core. Ozone treatment and disinfection — for clean and healthy air. Cabin filter replacement — quick and affordable.\n\nWhen Should You Visit a Shop?\n\nDon\'t wait for summer. The best time to check your AC is spring — March and April. Shops aren\'t busy, you can pick a convenient time, and prices for some services may be better. At HOT22, you can book online or call 089 338 3443. We\'re located in Varna and service cars of all makes.',
    date: '2026-02-20',
  },
  {
    slug: 'uv-test-techove',
    image: '/images/services/diagnostics.jpg',
    title_bg: 'UV тест за течове — защо е по-точен от класическите методи?',
    title_en: 'UV Leak Test — Why It\'s More Accurate Than Traditional Methods',
    excerpt_bg:
      'UV тестът за течове на климатичната система е най-точният метод за откриване дори на най-малки пропуски. Разберете как работи и защо превъзхожда сапунения тест и електронните детектори.',
    excerpt_en:
      'UV leak testing for AC systems is the most accurate method for finding even the smallest leaks. Learn how it works and why it outperforms soap tests and electronic detectors.',
    content_bg:
      'Течът на фреон е един от най-коварните проблеми в климатичната система. Може да заредите, а след месец фреонът отново да е изтекъл. Ключът е да се открие точно къде е течът — и тук UV тестът прави разликата.\n\nКакво е UV тест?\n\nUV тестът (ултравиолетов тест) е метод за откриване на течове, при който в климатичната система се добавя специална флуоресцентна боя. Тази боя циркулира заедно с фреона и маслото. Когато има теч, боята изтича заедно с фреона и оставя следа. С UV лампа (черна светлина) техникът сканира всички връзки, маркучи, кондензатора, изпарителя и компресора. Там, където има теч, боята свети ярко жълто-зелено — дори при теч от няколко грама на месец.\n\nСапунен тест — старият метод\n\nПри сапунения тест се нанася сапунен разтвор по подозрителните места и се наблюдава за мехурчета. Методът е прост и евтин, но има сериозни ограничения. Открива само течове при достатъчно налягане в системата. Не може да открие микро течове (под 20-30 г годишно). Не работи на труднодостъпни места. Неефективен при течове от изпарителя, който е скрит зад таблото.\n\nЕлектронен детектор — средно решение\n\nЕлектронният детектор засича молекули фреон във въздуха. Той е по-чувствителен от сапунения тест и може да открие по-малки течове. Но има и слабости: чувствителен е на вятър и вентилация, дава фалшиви аларми при замърсена среда, и показва зоната на теча, но не и точната точка. Използваме го в HOT22 като първи скрининг — бърз и удобен, но когато трябва да сме 100% сигурни, прибягваме до UV теста.\n\nКога да изберете UV тест?\n\nPrepоръчваме UV тест в следните ситуации: когато сте зареждали 2+ пъти за последната година и фреонът все изтича; когато електронният детектор не може да локализира точната точка на теча; при подозрение за теч от изпарителя; при покупка на кола с климатик, който „не държи" фреон; и при по-скъпи ремонти — за да сте сигурни, че ремонтирате правилното място.\n\nТочност на методите в сравнение\n\nСапунен тест открива течове над 50 г/годишно с точност около 60%. Електронен детектор открива течове над 15 г/годишно с точност 80-85%. UV тест открива течове от 5 г/годишно с точност над 95%. Разликата е очевидна — UV тестът е златният стандарт в индустрията.\n\nВ HOT22 предлагаме UV тест за течове като част от нашата диагностика. Ако имате проблем с изтичащ фреон, не залагайте на метода „заредете и се надявайте". Елате при нас — ще открием точно къде е течът и ще го отстраним. Обадете се на 089 338 3443.',
    content_en:
      'Refrigerant leaks are one of the trickiest problems in an AC system. You might recharge, and a month later the refrigerant has leaked out again. The key is finding exactly where the leak is — and that\'s where UV testing makes the difference.\n\nWhat Is a UV Test?\n\nA UV test (ultraviolet test) is a leak detection method where a special fluorescent dye is added to the AC system. This dye circulates together with the refrigerant and oil. When there\'s a leak, the dye escapes with the refrigerant and leaves a trace. Using a UV lamp (black light), the technician scans all fittings, hoses, the condenser, evaporator, and compressor. Where there\'s a leak, the dye glows bright yellow-green — even with leaks of just a few grams per month.\n\nSoap Test — The Old Method\n\nIn a soap test, soapy solution is applied to suspected areas and observed for bubbles. The method is simple and cheap but has serious limitations. It only detects leaks when there\'s sufficient pressure in the system. It can\'t find micro-leaks (under 20-30g per year). It doesn\'t work in hard-to-reach areas. It\'s ineffective for evaporator leaks, which are hidden behind the dashboard.\n\nElectronic Detector — The Middle Ground\n\nAn electronic detector senses refrigerant molecules in the air. It\'s more sensitive than the soap test and can find smaller leaks. But it has weaknesses too: it\'s sensitive to wind and ventilation, gives false alarms in contaminated environments, and shows the leak zone but not the exact point. We use it at HOT22 as a first screening — quick and convenient, but when we need to be 100% certain, we turn to UV testing.\n\nWhen Should You Choose a UV Test?\n\nWe recommend UV testing in these situations: when you\'ve recharged 2+ times in the past year and refrigerant keeps leaking; when the electronic detector can\'t pinpoint the exact leak location; when an evaporator leak is suspected; when buying a car with AC that \"doesn\'t hold\" refrigerant; and for more expensive repairs — to ensure you\'re fixing the right spot.\n\nAccuracy Comparison\n\nSoap test detects leaks above 50g/year with about 60% accuracy. Electronic detector finds leaks above 15g/year with 80-85% accuracy. UV test detects leaks from 5g/year with over 95% accuracy. The difference is clear — UV testing is the gold standard in the industry.\n\nAt HOT22, we offer UV leak testing as part of our diagnostics. If you have a recurring refrigerant leak problem, don\'t rely on the "recharge and hope" approach. Visit us — we\'ll find exactly where the leak is and fix it. Call 089 338 3443.',
    date: '2026-02-15',
  },
];
